version: '3'
services:
   elastic:
      image: elasticsearch:7.0.1
      container_name: elasticsearch
      environment:
         discovery.type: single-node
      ports:
         - 9200:9200
      networks:
         - esnet
   kibana:
      image: kibana:7.0.1
      container_name: kibana
      ports:
         - 5601:5601
      networks:
         - esnet
networks:
   esnet:
